// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/regent-themes/Cinematic.tsx": () => import("../components/mockups/regent-themes/Cinematic.tsx"),
  "./components/mockups/regent-themes/GlassPremium.tsx": () => import("../components/mockups/regent-themes/GlassPremium.tsx"),
  "./components/mockups/regent-themes/NeonPulse.tsx": () => import("../components/mockups/regent-themes/NeonPulse.tsx")
};
